### ISSUE TITLE
`Callback::call()` should be `unsafe` since it’s possible to call it without calling `.assert_legal()`

### ISSUE THREAD

**Issue by GoldsteinE** [pufferfish-rs/pufferfish#1]
Since `Callback` and `TypeMap` are both accessible from user code, code like this is unsound without using `unsafe`:
```rust
use pufferfish::{Callback, TypeMap};

let mut tm = TypeMap::new();
tm.insert(0_i32);
let f = |x: &mut i32, y: &mut i32| {
    assert!(std::ptr::eq(&*x, &*y)); // Two mutable pointers to the same place!
};
Callback::call(&f, &mut tm);
```

**Comment by lunabunn** [comment]
Thank you for the report! Fixed in ~~[ad7f12e](https://github.com/pufferfish-rs/pufferfish/commit/ad7f12e1e56fdf6b8da2c7aade091388eac16ebf)~~ [330a4b3](https://github.com/pufferfish-rs/pufferfish/commit/330a4b3aabe54eab8385d0c9c9b6c3129fa6822b).
